version: "3"

services:
  spark:
    image: docker.io/bitnami/spark
    user: root
    networks:
      dae:
        ipv4_address: 172.1.0.2
    environment:
      - PYTHONIOENCODING=utf8
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./src:/opt/bitnami/spark/src
  spark-worker-1:
    image: docker.io/bitnami/spark
    user: root
    networks:
      dae:
        ipv4_address: 172.1.0.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8081:8081"
    volumes:
      - ./src:/opt/bitnami/spark/src
  spark-worker-2:
    image: docker.io/bitnami/spark
    user: root
    networks:
      dae:
        ipv4_address: 172.1.0.4
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8082:8081"
    volumes:
      - ./src:/opt/bitnami/spark/src
  data_warehouse_db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data_warehouse
    restart: always
    networks:
      dae:
        ipv4_address: 172.1.0.20
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  application_db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: capstone
    restart: always
    networks:
      dae:
        ipv4_address: 172.1.0.21
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata_application_db:/var/lib/postgresql/data

networks:
  dae:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.1.0.0/24
