version: "3"

services:
  python1:
    image: "python:latest"
    build:
      context: ./
      dockerfile: ./Dockerfile

  python2:
    image: "python:latest"
    build:
      context: ./
      dockerfile: ./Dockerfile

spark:
    image: docker.io/bitnami/spark
    user: root
    networks:
      dae:
        ipv4_address: 172.1.0.2
    environment:
      - PYTHONIOENCODING=utf8
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
spark-worker-1:
  image: docker.io/bitnami/spark
  user: root
  networks:
    dae:
      ipv4_address: 172.1.0.3
  environment:
    - SPARK_MODE=worker
    - SPARK_MASTER_URL=spark://spark:7077
    - SPARK_WORKER_MEMORY=1G
    - SPARK_WORKER_CORES=1
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
spark-worker-2:
  image: docker.io/bitnami/spark
  user: root
  networks:
    dae:
      ipv4_address: 172.1.0.4
  environment:
    - SPARK_MODE=worker
    - SPARK_MASTER_URL=spark://spark:7077
    - SPARK_WORKER_MEMORY=1G
    - SPARK_WORKER_CORES=1
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no

networks:
  dae:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.1.0.0/24
