version: "3"

services:
  nestserver:
    environment:
      POSTGRES_USER: postgres
      DB_USERNAME: postgres

      POSTGRES_PASSWORD: postgres
      DB_PASSWORD: postgres

      POSTGRES_DB: capstone
      DB_NAME: capstone

      POSTGRES_HOST: postgres
      DB_HOST: postgres

      JWT_SECRET: very_secret_123
      NODE_ENV: production
      PORT: 8080
    depends_on:
      - postgres
    # build:
    #   context: ./
    #   dockerfile: ./Dockerfile
    image: onu941/docker-testing:latest
    ports:
      - "8080:8080"
  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: capstone
    ports:
      - "25433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
